server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    zookeeper:
      connect-string: 8.140.250.103:2181
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
#          filters:
#            - StripPrefix=1

me:
  auth:
    excludePaths:
      - /auth/**