server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    zookeeper:
      connect-string: 8.140.250.103:2181
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/videos/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**

me:
  auth:
    excludePaths:
      - /auth/**
      - /file/source/**

logging:
  level:
    root: INFO
    com.studio314: DEBUG